apiVersion: v1
kind: ConfigMap
metadata:
  name: lp-dor-node-configmap
data:
  lp_dor_node-z0-ci.properties: |-
    ENV_SSO_LP_DEFAULT_DOMAIN=https://lp_dor_node-ci.dev.lprnd.net
  lp_dor_node-z0-qa.properties: |-
    ENV_SSO_LP_DEFAULT_DOMAIN=https://lp_dor_node-qa.dev.lprnd.net
  lp_dor_node-z0-static-ci.properties: |-
     ENV_SSO_LP_DEFAULT_DOMAIN=https://lp_dor_node-static-ci.dev.lprnd.net
  lp_dor_node-z1-a.properties: |-
    ENV_SSO_LP_DEFAULT_DOMAIN=https://z1-a.lp_dor_node.liveperson.net
  lp_dor_node-z1-shared.properties: |-
    ENV_SSO_LP_DEFAULT_DOMAIN=https://z1-a.lp_dor_node.liveperson.net
  lp_dor_node-z2-shared.properties: |-
    ENV_SSO_LP_DEFAULT_DOMAIN=https://z2.lp_dor_node.liveperson.net