apiVersion: v1
kind: Service
metadata:
  name: lp-node-ci
  labels:
    name: lp-node-ci
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: app-service-port
  selector:
    lp_service: lp-dor-node
    lp_system: lp-dor
    lp_service_version: 1.0.18
    lp_tier: app
  type: NodePort
